export const HOSPITAL_IMAGES: Record<string, string> = {
  "wrexham-maelor-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/7/7f/Ysbyty_Maelor_Wrecsam._%28Wrexham_Maelor_Hospital%29_-_geograph.org.uk_-_161697.jpg",
  "the-grange-university-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/The_Grange_University_Hospital%2C_Llanfrechfa_%28geograph_6872256%29.jpg/960px-The_Grange_University_Hospital%2C_Llanfrechfa_%28geograph_6872256%29.jpg",
  "glangwili-general-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/d/d3/West_Wales_General_Hospital%2C_Glangwili%2C_Carmarthen_-_geograph.org.uk_-_21092.jpg",
  "prince-charles-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f5/Prince_Charles_Hospital_Rear.jpg/960px-Prince_Charles_Hospital_Rear.jpg",
  "morriston-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/4/44/Ysbyty_Treforys._Morriston_Hospital._-_geograph.org.uk_-_404965.jpg",
  "university-hospital-of-wales":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/a/ae/University_Hospital_of_Wales%2C_Heath_Park_-_Cardiff_-_geograph.org.uk_-_1736088.jpg/960px-University_Hospital_of_Wales%2C_Heath_Park_-_Cardiff_-_geograph.org.uk_-_1736088.jpg",
  "ysbyty-gwynedd":
    "https://upload.wikimedia.org/wikipedia/commons/5/58/Ysbyty_Gwynedd%2C_Bangor.jpg",
  "glan-clwyd-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/b/b5/The_new_facade_at_Ysbyty_Glan_Clwyd_2018_%28geograph_5882700%29.jpg",
  "royal-london-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bc/Royal_London_Hospital_redevelopment.jpg/960px-Royal_London_Hospital_redevelopment.jpg",
  "newham-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/4/4a/Newham_University_Hospital-_main_entrance_%28Geograph_1861636%29.jpg",
  "queen-elizabeth-hospital-woolwich":
    "https://upload.wikimedia.org/wikipedia/commons/0/07/Main_entrance%2C_Queen_Elizabeth_Hospital%2C_Woolwich.jpg",
  "queen-elizabeth-hospital-birmingham":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/b/bf/Queen_Elizabeth_Hospital_Birmingham%2C_Edgbaston%2C_Birmingham%2C_England-7March2011.jpg/960px-Queen_Elizabeth_Hospital_Birmingham%2C_Edgbaston%2C_Birmingham%2C_England-7March2011.jpg",
  "heartlands-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/3/39/Heartlands_Hospital_and_Heartlands_Treatment_Centre.jpg/960px-Heartlands_Hospital_and_Heartlands_Treatment_Centre.jpg",
  "good-hope-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/6/60/Good_Hope_Hospital_-_geograph.org.uk_-_30692.jpg",
  "william-harvey-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/e/ea/William_Harvey_Hospital%2C_Main_Entrance_-_geograph.org.uk_-_1236142.jpg",
  "maidstone-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/7/7f/Maidstone_Hospital.JPG",
  "queen-elizabeth-queen-mother-hospital-margate":
    "https://upload.wikimedia.org/wikipedia/commons/8/8a/QEQM_Hospital%2C_Margate_-_geograph.org.uk_-_991371.jpg",
  "derriford-hospital-plymouth":
    "https://upload.wikimedia.org/wikipedia/commons/e/e2/Derriford_Hospital.jpg",
  "royal-victoria-hospital-belfast":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Royal_Hospital_Belfast_02.jpg/960px-Royal_Hospital_Belfast_02.jpg",
  "ulster-hospital-dundonald":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Ulster_Hospital.JPG/960px-Ulster_Hospital.JPG",
  "craigavon-area-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/0/08/Craigavon_Area_Hospital_-_Front_Entrance_-_geograph.org.uk_-_1401867.jpg",
  "forth-valley-royal-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/1/17/Forth_Valley_Royal_close.jpg",
  "kent-and-canterbury-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/5/56/Kent_and_Canterbury_Hospital_-_geograph.org.uk_-_1334535.jpg",
  "bristol-royal-infirmary":
    "https://upload.wikimedia.org/wikipedia/commons/7/7a/Bristol_Royal_Infirmary.jpg",
  "manchester-royal-infirmary":
    "https://upload.wikimedia.org/wikipedia/commons/9/96/Manchester-Royal-Infirmary-Main-Entrance.JPG",
  "leeds-general-infirmary":
    "https://upload.wikimedia.org/wikipedia/commons/2/25/Jubilee_wing%2C_Leeds_General_Infirmary.jpg",
  "queens-medical-centre-nottingham":
    "https://upload.wikimedia.org/wikipedia/commons/4/4d/QMC_%28Queens_Medical_Centre%29_-_geograph.org.uk_-_680969.jpg",
  "royal-victoria-infirmary-newcastle":
    "https://upload.wikimedia.org/wikipedia/commons/5/5a/Peacock_Hall%2C_Royal_Victoria_Infirmary_-_geograph.org.uk_-_1762074.jpg",
  "whipps-cross-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/4/40/Whipps_Cross_Hospital_old_building.jpg",
  "homerton-urgent-treatment-centre":
    "https://upload.wikimedia.org/wikipedia/commons/1/12/Homerton_Hospital%2C_Hackney_-_geograph.org.uk_-_724458.jpg",
  "edgware-urgent-treatment-centre":
    "https://upload.wikimedia.org/wikipedia/commons/9/97/Edgware_Community_Hospital_-_geograph.org.uk_-_2290737.jpg",
  // Major English hospitals
  "aberdeen-royal-infirmary":
    "https://upload.wikimedia.org/wikipedia/commons/5/55/Main_Entrance_to_Aberdeen_Royal_Infirmary.jpg",
  "addenbrookes-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/5/55/Addenbrooke%27s_hospital.JPG",
  "aintree-university-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/7/7e/Aintree_University_Hospital_main_block_and_sign.jpg",
  "alexandra-hospital-redditch":
    "https://upload.wikimedia.org/wikipedia/commons/d/db/Alexandra_Hospital_Main_Entrance_-_geograph.org.uk_-_1717432.jpg",
  "charing-cross-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/6/64/Charing_Cross_Hospital_in_London%2C_spring_2013_%2815%29.JPG",
  "chelsea-and-westminster-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/f/f3/Chelsea_Westminster_Hospital_Front%2C_Fulham_Road.jpg",
  "cheltenham-general-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/c/c5/Cheltenham_General_Hospital_%28geograph_6292873%29.jpg",
  "croydon-university-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/8/8f/Croydon_University_Hospital.jpg",
  "freeman-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/a/a8/Entrance_to_Freeman_Hospital_-_geograph.org.uk_-_1127413.jpg",
  "glasgow-royal-infirmary":
    "https://upload.wikimedia.org/wikipedia/commons/0/0b/Glasgow_Royal_Infirmary_-_aerial_-_2025-04-17_01.jpg",
  "gloucestershire-royal-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/9/93/Gloucestershire_Royal_Hospital_-_geograph.org.uk_-_307768.jpg",
  "john-radcliffe-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/4/4f/The_John_Radcliffe_Hospital.jpg",
  "kings-college-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/2/24/King%27s_College_Hospital1.jpg",
  "leicester-royal-infirmary":
    "https://upload.wikimedia.org/wikipedia/commons/8/85/Royal_Infirmary%2C_Infirmary_Road%2C_Leicester_-_geograph.org.uk_-_7434151.jpg",
  "lincoln-county-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/f/fa/Lincoln_County_Hospital%2C_Lincoln_-_geograph.org.uk_-_1492725.jpg",
  "midland-metropolitan-university-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/e/e7/From_the_Secret_Garden_-_Midland_Metropolitan_Hospital.jpg",
  "milton-keynes-university-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/6/6e/MKUH_main_entrance_2019.jpg",
  "ninewells-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/8/8a/Ninewells_cropped.jpg",
  "norfolk-and-norwich-university-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/3/35/NHS_NNUH_entrance.jpg",
  "northampton-general-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/b/b4/Northampton_General_Hospital_%28geograph_2525604%29.jpg",
  "northern-general-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/9/98/Hadfield_Wing%2C_Northern_General_Hospital%2C_Sheffield_-_geograph.org.uk_-_1727565.jpg",
  "princess-royal-university-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/9/9a/Princess_Royal_Hospital%2C_Locksbottom.jpg",
  "queen-elizabeth-university-hospital-glasgow":
    "https://upload.wikimedia.org/wikipedia/commons/0/0b/NS5365_-_Queen_Elizabeth_University_Hospital.jpg",
  "royal-berkshire-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/8/82/Royal_Berkshire_Hospital_1.jpg",
  "royal-blackburn-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/3/34/Entrance_to_new_Royal_Blackburn_Hospital_-_geograph.org.uk_-_368126.jpg",
  "royal-cornwall-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/0/05/The_Royal_Cornwall_Hospital%2C_Treliske%2C_Truro_-_geograph.org.uk_-_89375.jpg",
  "royal-derby-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/2/2b/Royal_Derby_Hospital_Facade.jpg",
  "royal-infirmary-of-edinburgh":
    "https://upload.wikimedia.org/wikipedia/commons/1/12/Main_Entrance%2C_Edinburgh_Royal_Infirmary_-_geograph.org.uk_-_432996.jpg",
  "royal-liverpool-university-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/5/50/Mount_Vernon_Road_to_West_Derby_Street.jpg",
  "royal-preston-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/1/16/Royal_Preston_Hospital_-_geograph.org.uk_-_137786.jpg",
  "royal-shrewsbury-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/c/cf/Royal_Shrewsbury_Hospital_%28geograph_6270049%29.jpg",
  "royal-stoke-university-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/3/35/Royal_Stoke_University_Hospital_from_above.jpg",
  "royal-sussex-county-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/b/b2/Royal_Sussex_County_Hospital%2C_Brighton_-_geograph.org.uk_-_6384351.jpg",
  "sandwell-general-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/b/bb/Sandwell_General_Hospital_-_2016-08-16_-_Andy_Mabbett.jpg",
  "southampton-general-hospital":
    "https://upload.wikimedia.org/wikipedia/en/d/d9/Sgh_panorama.jpg",
  "southmead-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/c/c0/Southmead_Hospital%2C_Bristol-_north_end_of_Brunel_building_%28geograph_6010500%29.jpg",
  "st-georges-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/6/63/St.George%27s_Hospital%2C_Tooting_-_geograph.org.uk_-_2829072.jpg",
  "st-helier-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/8/8e/St._Helier_Hospital_%28geograph_3573272%29.jpg",
  "st-marys-hospital-london":
    "https://upload.wikimedia.org/wikipedia/commons/e/e1/St_Mary%27s_Hospital.jpg",
  "st-thomas-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/d/d3/St.thomas.hospital.arp.750pix.jpg",
  "torbay-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/b/bc/Torbay_Hospital_-_geograph.org.uk_-_3855429.jpg",
  "university-college-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/b/b5/University_College_Hospital_-_New_Building_-_London_-_020504.jpg",
  "university-hospital-coventry":
    "https://upload.wikimedia.org/wikipedia/commons/4/47/University_Hospital_Coventry%2C_main_entrance_4.21.jpg",
  "warrington-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/5/52/Monks_Street_-_geograph.org.uk_-_4633493.jpg",
  "west-middlesex-university-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/4/48/Royal_College_Of_Midwives_Picket_The_West_Middlesex_Hospital%2C_Isleworth_-_London.jpg",
  "whittington-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/2/2e/Whittington_Hospital_Magdala_Avenue_N19_5NF_-_geograph.org.uk_-_1062222.jpg",
  "worcestershire-royal-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/6/6a/Worcestershire_Royal_Hospital_-_geograph.org.uk_-_1203400.jpg",
  "worthing-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/5/56/Worthing_Hospital%2C_West_Sussex.jpg",
  // Small NI and community hospitals sourced from Geograph (CC BY-SA 2.0)
  "downe-hospital":
    "https://s0.geograph.org.uk/geophotos/02/53/28/2532868_99b43e92.jpg",
  "downe-hospital-phone-first-028-4483-8091-urgent-care-centre-minor-injuries":
    "https://s0.geograph.org.uk/geophotos/02/53/28/2532868_99b43e92.jpg",
  "faversham-utc":
    "https://s0.geograph.org.uk/geophotos/01/54/37/1543762_571bbbdb.jpg",
  "keswick-community-hospital":
    "https://s0.geograph.org.uk/geophotos/05/91/88/5918824_55debe2f.jpg",
  "penrith-community-hospital":
    "https://s0.geograph.org.uk/geophotos/03/59/52/3595205_88299247.jpg",
  "south-tyrone-hospital":
    "https://s0.geograph.org.uk/photos/25/89/258974_b4e5ed9f.jpg",
  "south-tyrone-hospital-phone-first-0300-123-3-111-minor-injury-unit":
    "https://s0.geograph.org.uk/photos/25/89/258974_b4e5ed9f.jpg",
  "lagan-valley-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/b/bf/Panoramic_view_of_Lagan_Valley_Hospital%2C_Lisburn_2014-04-18_03-33.jpg",
  // Small UTCs sourced from Geograph (CC BY-SA 2.0)
  "runcorn-urgent-treatment-centre":
    "https://s0.geograph.org.uk/photos/74/76/747632_9cbf5b4f.jpg",
  "victoria-hospital-deal":
    "https://s0.geograph.org.uk/photos/12/30/123085_df0519a0.jpg",
  // Remaining hospitals
  "borders-general-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/a/a3/Borders_General_Hospital%2C_Melrose_-_geograph.org.uk_-_372209.jpg",
  "buckland-hospital-dover":
    "https://upload.wikimedia.org/wikipedia/commons/2/24/New_Buckland_Hospital%2C_Coombe_Valley_Road_-_geograph.org.uk_-_5105747.jpg",
  "lagan-valley-hospital-phone-first-028-9260-4643-urgent-care-centre":
    "https://upload.wikimedia.org/wikipedia/commons/b/bf/Panoramic_view_of_Lagan_Valley_Hospital%2C_Lisburn_2014-04-18_03-33.jpg",
  "omagh-hospital-and-primary-care-complex-urgent-care-and-treatment-centre":
    "https://upload.wikimedia.org/wikipedia/commons/f/f5/Omagh_Hospital_%26_Primary_Care_Complex_%28geograph_5969491%29.jpg",
  "princess-royal-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/8/8c/Main_Entrance_to_Princess_Royal_Hospital_%28geograph_3592604%29.jpg",
  "royal-victoria-hospital-folkestone":
    "https://upload.wikimedia.org/wikipedia/commons/3/39/Royal_Victoria_Hospital%2C_Radnor_Park_Avenue_-_geograph.org.uk_-_3899763.jpg",
  // More English hospitals
  "burnley-general-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/f/fb/Burnley_General_Hospital_-_geograph.org.uk_-_7649.jpg",
  "chorley-and-south-ribble-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/8/86/Main_entrance_to_Chorley_District_Hospital_-_geograph.org.uk_-_3065308.jpg",
  "county-hospital-stafford":
    "https://upload.wikimedia.org/wikipedia/commons/5/54/Stafford_Hospital_Overview.jpg",
  "cumberland-infirmary-carlisle":
    "https://upload.wikimedia.org/wikipedia/commons/7/70/Cumberland_Infirmary%2C_Carlisle_-_geograph.org.uk_-_74610.jpg",
  "furness-general-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/c/ce/Barrow_Hospital_-_geograph.org.uk_-_479591.jpg",
  "grantham-and-district-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/a/a6/Grantham_%26_Kesteven_Hospital_-_geograph.org.uk_-_1986252.jpg",
  "hereford-county-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/8/8e/Hereford_County_Hospital_-_geograph.org.uk_-_5708481.jpg",
  "horton-general-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/d/d9/Horton_Hospital%2C_Banbury.jpg",
  "leighton-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/9/94/Leighton_-_Leighton_Hospital_Reception.jpg",
  "pilgrim-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/5/5f/Pilgrim_Hospital%2C_Boston_-_geograph.org.uk_-_786005.jpg",
  "princess-royal-hospital-telford":
    "https://upload.wikimedia.org/wikipedia/commons/5/5d/Entrance_to_Telford_Hospital_-_geograph.org.uk_-_980554.jpg",
  "queens-hospital-burton":
    "https://upload.wikimedia.org/wikipedia/commons/8/88/Queens_Hospital%2C_Burton-_Tom_Davies_House_%28geograph_4444813%29.jpg",
  "royal-lancaster-infirmary":
    "https://upload.wikimedia.org/wikipedia/commons/1/16/Royal_Lancaster_Infirmary_%28original_building%29.jpg",
  "solihull-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/5/56/Solihull_Hospital_-_geograph.org.uk_-_26247.jpg",
  "st-richards-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/b/b1/St_Richard%27s_Hospital%2C_West_Sussex.jpg",
  "tunbridge-wells-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/5/51/Pembury_Hospital_-_geograph.org.uk_-_5596152.jpg",
  "west-cumberland-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/a/ab/West_Cumberland_Hospital_-_geograph.org.uk_-_79516.jpg",
  "westmorland-general-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/0/0a/Car_Park_Westmorland_General_Hospital_-_geograph.org.uk_-_104952.jpg",
  // Scottish hospitals
  "dr-grays-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/0/0b/Dr_Grays_Hospital.jpg",
  "dumfries-and-galloway-royal-infirmary":
    "https://upload.wikimedia.org/wikipedia/commons/9/97/Dumfries_and_Galloway_Royal_Infirmary.jpg",
  "hairmyres-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/b/bc/Hairmyres_Hospital.jpg",
  "perth-royal-infirmary":
    "https://upload.wikimedia.org/wikipedia/commons/f/fd/Perth_Royal_Infirmary_-_geograph.org.uk_-_20506.jpg",
  "raigmore-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/1/14/Raigmore_Hospital%2C_Inverness%2C_Scotland.jpg",
  "royal-alexandra-hospital-paisley":
    "https://upload.wikimedia.org/wikipedia/commons/1/19/Royal_Alexandria_Hospital_Paisley._-_geograph.org.uk_-_242264.jpg",
  "st-johns-hospital-livingston":
    "https://upload.wikimedia.org/wikipedia/commons/9/9c/St_Johns_Hospital_2025_07.jpg",
  "university-hospital-ayr":
    "https://upload.wikimedia.org/wikipedia/commons/b/b2/University_Hospital%2C_Ayr.jpg",
  "university-hospital-crosshouse":
    "https://upload.wikimedia.org/wikipedia/commons/b/bf/University_Hospital_Crosshouse_entrance.jpg",
  "university-hospital-monklands":
    "https://upload.wikimedia.org/wikipedia/commons/1/19/Monklands_Hospital_-_geograph.org.uk_-_370538.jpg",
  "university-hospital-wishaw":
    "https://upload.wikimedia.org/wikipedia/commons/2/2d/Wishaw_General_Hospital_-_geograph.co.uk_-_2576401.jpg",
  "victoria-hospital-kirkcaldy":
    "https://upload.wikimedia.org/wikipedia/commons/1/11/The_New_Vic_-_geograph.org.uk_-_2895013.jpg",
  "western-general-hospital-edinburgh":
    "https://upload.wikimedia.org/wikipedia/commons/f/f5/Western_General_clock_tower_-_geograph.org.uk_-_1770603.jpg",
  // Northern Ireland - new slugs with -emergency-department suffix
  "altnagelvin-area-hospital-emergency-department":
    "https://upload.wikimedia.org/wikipedia/commons/5/55/Altnagelvin_Area_Hospital_SMC_2011.JPG",
  "antrim-area-hospital-emergency-department":
    "https://upload.wikimedia.org/wikipedia/commons/a/af/Antrim_Hospital%2C_Antrim_-_geograph.org.uk_-_428570.jpg",
  "causeway-area-hospital-emergency-department":
    "https://upload.wikimedia.org/wikipedia/commons/7/70/Causeway_Hospital_-_geograph.org.uk_-_1154836.jpg",
  "daisy-hill-hospital-emergency-department":
    "https://upload.wikimedia.org/wikipedia/commons/f/f1/Newrys_Daisy_Hill_Hospital_towering_above_Camlough_Road_%28geograph_3505805%29.jpg",
  "mater-hospital-emergency-department":
    "https://upload.wikimedia.org/wikipedia/commons/8/83/Mater_Infirmorum_Hospital.png",
  "royal-children-s-hospital-emergency-department":
    "https://upload.wikimedia.org/wikipedia/commons/2/28/Construction_work_at_the_Royal_Belfast_Hospital_for_Sick_Children_%28geograph_6193614%29.jpg",
  "south-west-acute-hospital-emergency-department":
    "https://upload.wikimedia.org/wikipedia/commons/4/45/South_West_Acute_Hospital_near_Enniskillen.jpg",
  "craigavon-area-hospital-emergency-department":
    "https://upload.wikimedia.org/wikipedia/commons/0/08/Craigavon_Area_Hospital_-_Front_Entrance_-_geograph.org.uk_-_1401867.jpg",
  "royal-victoria-hospital-emergency-department":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/5/5a/Royal_Hospital_Belfast_02.jpg/960px-Royal_Hospital_Belfast_02.jpg",
  "ulster-hospital-emergency-department":
    "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9d/Ulster_Hospital.JPG/960px-Ulster_Hospital.JPG",
  // Forth Valley MIU - same building as main hospital
  "forth-valley-royal-hospital-miu":
    "https://upload.wikimedia.org/wikipedia/commons/1/17/Forth_Valley_Royal_close.jpg",
  // Derriford Plymouth - same building, different slug
  "derriford-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/e/e2/Derriford_Hospital.jpg",
  // QEQM Margate - same as queen-elizabeth-queen-mother-hospital-margate
  "qeqm-hospital-margate":
    "https://upload.wikimedia.org/wikipedia/commons/8/8a/QEQM_Hospital%2C_Margate_-_geograph.org.uk_-_991371.jpg",
  "causeway-area-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/7/70/Causeway_Hospital_-_geograph.org.uk_-_1154836.jpg",
  "herne-bay-utc":
    "https://upload.wikimedia.org/wikipedia/commons/2/2f/Queen_Victoria_Memorial_Hospital%2C_Herne_Bay_-_geograph.org.uk_-_1334586.jpg",
  "kings-mill-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/6/60/King%27s_Mill_Hospital_and_Reservoir_cropped.JPG",
  "kingsbridge-miu":
    "https://upload.wikimedia.org/wikipedia/commons/d/d2/Kingsbridge_Community_Hospital_%28geograph_5930428%29.jpg",
  "liskeard-miu":
    "https://upload.wikimedia.org/wikipedia/commons/3/39/Liskeard_Community_Hospital_-_geograph.org.uk_-_171788.jpg",
  "newton-abbot-community-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/b/b6/Newton_Abbot_Community_Hospital.jpg",
  "north-manchester-general-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/f/f0/North_Manchester_General_Hospital_-_geograph.org.uk_-_3747034.jpg",
  "omagh-hospital-and-primary-care-complex":
    "https://upload.wikimedia.org/wikipedia/commons/f/f5/Omagh_Hospital_%26_Primary_Care_Complex_%28geograph_5969491%29.jpg",
  "royal-victoria-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/f/f3/Royal_Victoria_Hospital_in_Belfast.jpg",
  "st-jamess-university-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/4/4b/St_James%27s_University_Hospital%2C_Leeds_-_geograph.org.uk_-_5016174.jpg",
  "ulster-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/3/3b/Ulster_Hospital%2C_Dundonald_-_geograph.org.uk_-_791361.jpg",
  "university-hospital-coventry-childrens-ae":
    "https://upload.wikimedia.org/wikipedia/commons/4/47/University_Hospital_Coventry%2C_main_entrance_4.21.jpg",
  "university-hospital-coventry-emergency-gynaecology":
    "https://upload.wikimedia.org/wikipedia/commons/4/47/University_Hospital_Coventry%2C_main_entrance_4.21.jpg",
  "university-hospital-coventry-miu":
    "https://upload.wikimedia.org/wikipedia/commons/4/47/University_Hospital_Coventry%2C_main_entrance_4.21.jpg",
  "wythenshawe-hospital":
    "https://upload.wikimedia.org/wikipedia/commons/2/2d/UHSMentrance.jpg",
  "falmouth-miu":
    "https://upload.wikimedia.org/wikipedia/commons/7/78/Falmouth_Hospital_%2823949528135%29.jpg",
  "stratton-miu":
    "https://upload.wikimedia.org/wikipedia/commons/f/f3/Stratton_hospital_-_geograph.org.uk_-_5547123.jpg",
};

export function getHospitalImage(slug: string): string | null {
  return HOSPITAL_IMAGES[slug] ?? null;
}
